name: Validate Azure Credentials

on:
  workflow_dispatch

jobs:
  checkAzureSecret:
    runs-on: ubuntu-latest
    steps:
      - name: Test Secret Accessibility
        run: |
          if [[ -z "${{ secrets.AZURE_CREDENTIALS }}" ]]; then
            echo "❌ Secret is missing!"
            exit 1
          else
            echo "✅ Secret is available!"
          fi

      - name: Azure Login Test
        run: |
          az login --service-principal \
          --username $(jq -r '.clientId' <<< '${{ secrets.AZURE_CREDENTIALS }}') \
          --password $(jq -r '.clientSecret' <<< '${{ secrets.AZURE_CREDENTIALS }}') \
          --tenant $(jq -r '.tenantId' <<< '${{ secrets.AZURE_CREDENTIALS }}')

      - name: Verify Subscription Access
        run: az account show
