name: Connect to AKS

on:
  workflow_dispatch

jobs:
  connectAKS:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1.4.6
        with:
          client-id: ${{ secrets.AZURE_CREDENTIALS}}
          tenant-id: ${{ secrets.AZURE_CREDENTIALS }}
          subscription-id: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set up AKS Context
        uses: azure/aks-set-context@v3
        with:
          resource-group: ${{ env.RESOURCE_GROUP }}
          cluster-name: ${{ env.CLUSTER_NAME }}
          admin: 'false'
          use-kubelogin: 'true'

      - name: Verify Connection
        run: kubectl get pods

      - name: Show Nodes
        run: kubectl get nodes